%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

%global __cmake_in_source_build 1

Name:           ros-humble-rclcpp
Version:        16.0.16
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rclcpp package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-humble-ament-index-cpp
Requires:       ros-humble-builtin-interfaces
Requires:       ros-humble-libstatistics-collector
Requires:       ros-humble-rcl
Requires:       ros-humble-rcl-interfaces
Requires:       ros-humble-rcl-yaml-param-parser
Requires:       ros-humble-rcpputils
Requires:       ros-humble-rcutils
Requires:       ros-humble-rmw
Requires:       ros-humble-rosgraph-msgs
Requires:       ros-humble-rosidl-runtime-cpp
Requires:       ros-humble-rosidl-typesupport-c
Requires:       ros-humble-rosidl-typesupport-cpp
Requires:       ros-humble-statistics-msgs
Requires:       ros-humble-tracetools
Requires:       ros-humble-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-humble-ament-cmake-gen-version-h
BuildRequires:  ros-humble-ament-cmake-ros
BuildRequires:  ros-humble-ament-index-cpp
BuildRequires:  ros-humble-builtin-interfaces
BuildRequires:  ros-humble-libstatistics-collector
BuildRequires:  ros-humble-rcl
BuildRequires:  ros-humble-rcl-interfaces
BuildRequires:  ros-humble-rcl-yaml-param-parser
BuildRequires:  ros-humble-rcpputils
BuildRequires:  ros-humble-rcutils
BuildRequires:  ros-humble-rmw
BuildRequires:  ros-humble-rosgraph-msgs
BuildRequires:  ros-humble-rosidl-runtime-cpp
BuildRequires:  ros-humble-rosidl-typesupport-c
BuildRequires:  ros-humble-rosidl-typesupport-cpp
BuildRequires:  ros-humble-statistics-msgs
BuildRequires:  ros-humble-tracetools
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-humble-ament-cmake-gmock
BuildRequires:  ros-humble-ament-cmake-google-benchmark
BuildRequires:  ros-humble-ament-cmake-gtest
BuildRequires:  ros-humble-ament-lint-auto
BuildRequires:  ros-humble-ament-lint-common
BuildRequires:  ros-humble-mimick-vendor
BuildRequires:  ros-humble-performance-test-fixture
BuildRequires:  ros-humble-rmw-implementation-cmake
BuildRequires:  ros-humble-rosidl-default-generators
BuildRequires:  ros-humble-test-msgs
%endif

%description
The ROS client library in C++.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DAMENT_PREFIX_PATH="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Tue Nov 18 2025 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.16-1
- Autogenerated by Bloom

* Thu Sep 11 2025 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.15-1
- Autogenerated by Bloom

* Wed Jul 16 2025 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.14-1
- Autogenerated by Bloom

* Mon Jun 23 2025 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.13-1
- Autogenerated by Bloom

* Tue Mar 25 2025 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.12-1
- Autogenerated by Bloom

* Mon Nov 25 2024 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.11-1
- Autogenerated by Bloom

* Fri Jul 26 2024 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.10-1
- Autogenerated by Bloom

* Wed May 15 2024 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.9-1
- Autogenerated by Bloom

* Wed Jan 24 2024 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.8-1
- Autogenerated by Bloom

* Mon Nov 13 2023 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.7-1
- Autogenerated by Bloom

* Tue Sep 19 2023 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.6-1
- Autogenerated by Bloom

* Tue Jul 18 2023 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.5-2
- Autogenerated by Bloom

* Mon Jul 17 2023 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.5-1
- Autogenerated by Bloom

* Tue Apr 25 2023 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.4-2
- Autogenerated by Bloom

* Tue Apr 25 2023 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.4-1
- Autogenerated by Bloom

* Tue Jan 10 2023 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.3-1
- Autogenerated by Bloom

* Mon Nov 07 2022 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.2-1
- Autogenerated by Bloom

* Tue Apr 19 2022 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.1-2
- Autogenerated by Bloom

* Wed Apr 13 2022 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.1-1
- Autogenerated by Bloom

* Fri Apr 08 2022 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 16.0.0-1
- Autogenerated by Bloom

* Tue Apr 05 2022 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 15.4.0-1
- Autogenerated by Bloom

* Wed Mar 30 2022 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 15.3.0-1
- Autogenerated by Bloom

* Thu Mar 24 2022 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 15.2.0-1
- Autogenerated by Bloom

* Tue Mar 01 2022 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 15.1.0-1
- Autogenerated by Bloom

* Tue Feb 08 2022 Ivan Paunovic <ivanpauno@ekumenlabs.com> - 15.0.0-2
- Autogenerated by Bloom

